target-version = "py311"
line-length = 100

[lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
]
ignore = [
    "E501", # let line-length be handled by formatter or selectively
    "E402", # allow late imports for env setup in main.py
]

[lint.isort]
known-first-party = ["backend"]
force-sort-within-sections = true

[format]
quote-style = "single"